[build]
    publish = "public"

[[redirects]]
    from = "/cache-tag"
    to = "/.netlify/functions/cache-tag"
    status = 200
    force = true

[[redirects]]
    from = "/netlify-cache-tag"
    to = "/.netlify/functions/netlify-cache-tag"
    status = 200
    force = true

[[redirects]]
    from = "/purge"
    to = "/.netlify/functions/purge"
    status = 200
    force = true
